### ISSUE TITLE
Google Takeout not detected

### ISSUE THREAD

**Issue by mbolli** [timelinize/timelinize#24]
I get the following alert when it tries to detect the type of `takeout-20240816T155240Z-001.tgz` (95 MB) 

```json
{"response":{},"error":{"http_status":500,"message":"context deadline exceeded","recommendations":["Make any relevant changes, then try again.","If it still doesn't work, we can help! Please report this bug along with this magic incantation: 9ehb734s to support@dyanim.com and we'll take care of it."],"id":"9ehb734s","error":"context deadline exceeded"}}
```

**Comment by mholt** [comment]
That is weird... it's not even a big file. This usually happens when a folder or archive contains a lot of files and some of the data sources have to recursively scan all of them to decide if it is recognized. But for smaller folders like that it should be fast... I assume there's not 10000 little files?

In any case, I've been revising the import flow to resolve this in a branch.

**Comment by mbolli** [comment]
When randomly list some folders, I saw the possible culprit:

The `Takeout/Location History (Timeline)/Records.json` file is 1.3 GB unzipped. Could be it?

**Comment by mholt** [comment]
Unlikely, I also have a lot in there and it does compress pretty well. We don't read the whole files, just the file listing and enough of the file to know if we can open it (that may even just be the file name). So a large file should be no problem.

**Comment by aswwwanth** [comment]
I am also getting the same error. In my case the takeout is 8.61 GB (it includes photos) 

```json
{"response":{},"error":{"http_status":500,"message":"context deadline exceeded","recommendations":["Make any relevant changes, then try again.","If it still doesn't work, we can help! Please report this bug along with this magic incantation: sr5yxtrf to support@dyanim.com and we'll take care of it."],"id":"sr5yxtrf","error":"context deadline exceeded"}}
```

**Comment by aswwwanth** [comment]
Hey, no problem - I know it's like an alpha version. Not frustrating at all.

> Or set it to 0 for none.

I tried after setting it 0. It took some time and the API errored out I think

```
2024/08/21 17:31:31.268	INFO	http: panic serving 127.0.0.1:64011: runtime error: index out of range [0] with length 0
goroutine 24 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1898 +0xbe
panic({0x10df2bd40?, 0xc0004e20d8?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/mholt/archiver/v4.ArchiveFS.Stat({{0xc000860540, 0x3b}, 0x0, {0x11320d608, 0xc0008053c0}, {0x0, 0x0}, {0x10e0481f8, 0x10efac720}}, {0x10d020f5e, ...})
```

I can wait for the new import flow changes

**Comment by mholt** [comment]
@aswwwanth That looks like a bug in the `archiver` project. I _think_ it should be fixed in this commit: https://github.com/mholt/archiver/commit/743ede3881bb34d43b9ca063232367cbc237daea

You can do `go get github.com/mholt/archiver@743ede3881bb34d43b9ca063232367cbc237daea` (and then `go mod tidy` I guess) and see if that helps with the panic you reported.

**Comment by aswwwanth** [comment]
I am sorry this is turning out to be a bag of worms 😅 

I tried again after pinning the version of `archiver`. Now it's been loading for like 15-20 mins and my RAM usage is spiking. 
Could this be because of the huge (8.6 GB) takeout archive? I can try one without photos

**Comment by mholt** [comment]
Hmm no the size shouldn't matter. I've got another bug. Can you go to http://localhost:12002/debug/pprof while it's doing that and capture heap and goroutine profiles? That will help me know what is going on.

Thanks for your patience and help! I want to get this right!

**Comment by aswwwanth** [comment]
Here you go,
[goroutine.txt](https://github.com/user-attachments/files/16697930/goroutine.txt)
[heap.txt](https://github.com/user-attachments/files/16697933/heap.txt)

Happy to help!

**Comment by mholt** [comment]
Thanks, so it looks like a lot of the allocations are coming from reading the directory in the archive. Maybe another bug in the archiver lib, but I don't know how to learn more without potentially having a copy of the archive. @mbolli Yours is smaller, does yours have this same issue now?

**Comment by mbolli** [comment]
Actually with archiver pinned on the commit and `timeout=0` the archive is detected successfully

**Comment by aswwwanth** [comment]
> Could this be because of the huge (8.6 GB) takeout archive? I can try one without photos

I tried with a smaller takeout - 1.4GB (without the photos). It was properly detected in less than a second and I was able to import it as well

**Comment by mholt** [comment]
@aswwwanth @mbolli When fixing linter errors this week I noticed one of them related to this context, so it's possible I fixed a bug (?) here. Do you want to try again with the latest on main?

**Comment by mbolli** [comment]
@mholt On main I unfortunately still get `Error: {"response":{},"error":{"http_status":500,"message":"context deadline exceeded","recommendations":["Make any relevant changes, then try again.","If it still doesn't work, we can help! Please report this bug along with this magic incantation: 6rnaxw8b to support@dyanim.com and we'll take care of it."],"id":"6rnaxw8b","error":"context deadline exceeded"}}` with my 96 MB takeout file.

**Comment by mholt** [comment]
Ok. Darn, thanks for checking though. Work is under way in a branch to revise the import flow that will fix this (promise!)

**Comment by aswwwanth** [comment]
@mholt I am having a different behaviour. 

This is what I got when I tried my original takeout with photos. 
<img width="714" alt="image" src="https://github.com/user-attachments/assets/3ca5ee0a-6952-4626-a4ff-26ba3dfaa791">

**Comment by mholt** [comment]
Ahh weird :upside_down_face: It's definitely broken for that archive for some reason.

I would still love to find out what, since I think it's a bug in my archiver project, but hard to do without the actual archive (which, of course, probably has all sorts of personal data, so that's understandable).

Anyway, the new flow won't work like this, so I'm hoping it will solve the problem. But if the bug in archiver pertains more to reading the archive than to traversing it, the problem may persist.

**Comment by mholt** [comment]
@aswwwanth Could you start fresh with the latest on main and try importing again? I've revised the import flow entirely and even rewritten a fair amount of the `archives` package (formerly `archiver`) to be more capable and ... correct, I believe. I'm hopeful the issue may be resolved.

**Comment by mholt** [comment]
Closing due to inactivity. The code base related to this issue has been completely revised/rewritten, so I would be interested to know if the bug still exists.
